/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author FireBlazeTSETSR
 */
public class FilmOsebaInsert extends javax.swing.JFrame {

    /**
     * Creates new form FilmOsebaInsert
     */
    public FilmOsebaInsert() {
        initComponents();
        fillMenus();
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Film:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 260, -1));

        jLabel2.setText("Person:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 260, -1));

        jToggleButton1.setText("Insert new role");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 30));

        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setText("Role:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, -1));

        jButton1.setText("Insert!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            jTextField1.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jComboBox3.setVisible(false);
        } else {
            jTextField1.setVisible(!true);
            jLabel3.setVisible(!true);
            jLabel4.setVisible(!false);
            jComboBox3.setVisible(!false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "The name must not be empty!");
                return;
            }
            try {
                Connection con = OracleConnection.getConnection();
                Statement stm = null;
                con.setAutoCommit(false);
                ResultSet rs = null;
                stm = con.createStatement();

                rs = stm.executeQuery("select distinct vloga from FILM_OSEBA\n"
                        + "order by vloga asc");
                con.commit();
                while (rs.next()) {
                    if (rs.getString(1).equals(jTextField1.getText())) {
                        JOptionPane.showMessageDialog(this, "The role with that name already exists!");
                        return;
                    }

                }
                rs.close();
                
                
                stm.execute("insert into FILM_OSEBA(IDFILM, IDOSEBA, VLOGA)\n"
                        + "VALUES(" + Integer.parseInt(jComboBox1.getSelectedItem().toString().substring(0, jComboBox1.getSelectedItem().toString().indexOf(","))) + ","
                        + Integer.parseInt(jComboBox2.getSelectedItem().toString().substring(0, jComboBox2.getSelectedItem().toString().indexOf(","))) + ",'"
                        +jTextField1.getText().replace("'", "''")+"')");
                con.commit();

                stm.close();
                con.close();
                
                                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedItem(0);
                jTextField1.setText(null);
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            fillMenus();
            jTextField1.setText(null);
        } else {
            try {
                Connection con = OracleConnection.getConnection();
                Statement stm = null;
                con.setAutoCommit(false);
                stm = con.createStatement();

                stm.execute("insert into FILM_OSEBA(IDFILM, IDOSEBA, VLOGA)\n"
                        + "VALUES(" + Integer.parseInt(jComboBox1.getSelectedItem().toString().substring(0, jComboBox1.getSelectedItem().toString().indexOf(","))) + ","
                        + Integer.parseInt(jComboBox2.getSelectedItem().toString().substring(0, jComboBox2.getSelectedItem().toString().indexOf(","))) + ",'"
                        + jComboBox3.getSelectedItem().toString() + "')");
                con.commit();
                stm.close();
                con.close();
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedItem(0);
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmOsebaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmOsebaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmOsebaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmOsebaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmOsebaInsert().setVisible(true);
            }
        });
    }

    private void fillMenus() {
        try {
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;
            con.setAutoCommit(false);
            stm = con.createStatement();
            rs = stm.executeQuery("select IDFILM, ime from FILM\n"
                    + "order by idfilm");
            con.commit();

            while (rs.next()) {
                jComboBox1.addItem(rs.getInt(1) + "," + rs.getString(2));
            }

            rs = stm.executeQuery("select IDOSEBA, ime, priimek from oseba\n"
                    + "order by IDOSEBA");

            while (rs.next()) {
                jComboBox2.addItem(rs.getInt(1) + "," + rs.getString(2) + " " + rs.getString(3));
            }

            rs = stm.executeQuery("select distinct vloga from FILM_OSEBA\n"
                    + "order by vloga asc");

            while (rs.next()) {
                jComboBox3.addItem(rs.getString(1));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
