/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author n3-21
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jButton1.setText("LOGIN!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        setSize(new java.awt.Dimension(416, 333));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean prijavljen = false;
        boolean praznoPolje=false;
        String strUser;
        char[] tabelaGeslo;
        String strGeslo = "";

        Connection connection = OracleConnection.getConnection();
        Statement stmt = null;
        ResultSet rs = null;
        String strSql = "";

        strSql = "select iduser, usn, passwd, name, surname,IDRIGHTS from users";
        strUser = jTextField1.getText();

        tabelaGeslo = jPasswordField1.getPassword();
        //tabelo znakov spremenimo v Strung
        for (int i = 0; i < tabelaGeslo.length; i++) {
            strGeslo = strGeslo + tabelaGeslo[i];
        }

        strGeslo = StaticVars.getMd5(strGeslo);
        if (jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty()) {
            praznoPolje=true;
        } else
        try {

            stmt = connection.createStatement();
            rs = stmt.executeQuery(strSql);
            while (rs.next()) {

                if (strUser.equals(rs.getString("usn")) && strGeslo.equals(rs.getString("passwd"))) {
                    //prijavljen
                    prijavljen = true;
                    StaticVars.g_strUserID = rs.getString(1);
                    StaticVars.g_strUser = rs.getString("usn");
                    StaticVars.g_strPassword = rs.getString("passwd");
                    StaticVars.g_strRole = rs.getInt("IDRIGHTS")+"";
                    StaticVars.g_strIme = rs.getString("name");
                    StaticVars.g_strPriimek = rs.getString("surname");
                    break;
                }
            }

        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "DB connection error.");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } finally {
            try {
                stmt.close();
            } catch (Exception e) {
            }
            try {
                rs.close();
            } catch (Exception e) {
            }
            try {
                connection.close();
            } catch (Exception e) {
            }
        }

        if(praznoPolje==true){
            JOptionPane.showMessageDialog(rootPane, "Prazna polja");
        }
        else if (prijavljen == false) {
            JOptionPane.showMessageDialog(this, "Napačno uporabniško ime ali geslo!");
        } else {
            //skok v novo okno
            JOptionPane.showMessageDialog(this, "Welcome " + StaticVars.g_strIme + " "
                    + StaticVars.g_strPriimek + "!");
            
            new MainOverview().setVisible(true);
            dispose();
        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FirstScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
     if(evt.getKeyCode()==10){
         boolean prijavljen = false;
        boolean praznoPolje=false;
        String strUser;
        char[] tabelaGeslo;
        String strGeslo = "";

        Connection connection = OracleConnection.getConnection();
        Statement stmt = null;
        ResultSet rs = null;
        String strSql = "";

        strSql = "select iduser, usn, passwd, name, surname,IDRIGHTS from users";
        strUser = jTextField1.getText();

        tabelaGeslo = jPasswordField1.getPassword();
        //tabelo znakov spremenimo v Strung
        for (int i = 0; i < tabelaGeslo.length; i++) {
            strGeslo = strGeslo + tabelaGeslo[i];
        }

        strGeslo = StaticVars.getMd5(strGeslo);
        if (jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty()) {
            praznoPolje=true;
        } else
        try {

            stmt = connection.createStatement();
            rs = stmt.executeQuery(strSql);
            while (rs.next()) {

                if (strUser.equals(rs.getString("usn")) && strGeslo.equals(rs.getString("passwd"))) {
                    //prijavljen
                    prijavljen = true;
                    StaticVars.g_strUserID = rs.getString(1);
                    StaticVars.g_strUser = rs.getString("usn");
                    StaticVars.g_strPassword = rs.getString("passwd");
                    StaticVars.g_strRole = rs.getInt("IDRIGHTS")+"";
                    StaticVars.g_strIme = rs.getString("name");
                    StaticVars.g_strPriimek = rs.getString("surname");
                    break;
                }
            }

        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "DB connection error.");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } finally {
            try {
                stmt.close();
            } catch (Exception e) {
            }
            try {
                rs.close();
            } catch (Exception e) {
            }
            try {
                connection.close();
            } catch (Exception e) {
            }
        }

        if(praznoPolje==true){
            JOptionPane.showMessageDialog(rootPane, "Some fields are empty!");
        }
        else if (prijavljen == false) {
            JOptionPane.showMessageDialog(this, "Incorrect username or password!");
        } else {
            //skok v novo okno
            JOptionPane.showMessageDialog(this, "Welcome " + StaticVars.g_strIme + " "
                    + StaticVars.g_strPriimek + "!");
            
            new MainOverview().setVisible(true);
            dispose();
        }
     }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
