/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author n3-21
 */
public class MainOverview extends javax.swing.JFrame {

    static int SelectedTable = 0;

    /**
     * Creates new form MainOverview
     */
    public MainOverview() {
        initComponents();
        adjustView();
        jTable1.setEnabled(false);
        jButton22.setVisible(false);
        jButton23.setVisible(false);
        jToggleButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 275));

        jLabel1.setText("Write Out data:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jButton1.setText("Time table of movies");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jButton2.setText("Halls");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, -1));

        jButton3.setText("Movies");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, -1));

        jButton4.setText("FILM_PERSON");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, -1));

        jButton5.setText("Personel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, -1));

        jButton6.setText("Genre");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 140, -1));

        jButton7.setText("Ticket");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 140, -1));

        jButton8.setText("Customer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 140, -1));

        jButton9.setText("Reviews");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 140, -1));

        jLabel2.setText("Insert into:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jButton10.setText("Time table");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 100, -1));

        jButton11.setText("Hall");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 100, -1));

        jButton12.setText("Movie");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, -1));

        jButton13.setText("Film_person");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, -1));

        jButton14.setText("Personel");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 100, -1));

        jButton15.setText("Genre");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 100, -1));

        jButton16.setText("Ticket");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 100, -1));

        jButton17.setText("Customer");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 100, -1));

        jButton18.setText("Review");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 100, -1));

        jLabel3.setText("Advanced Options:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        jButton19.setText("User premissions");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 140, -1));

        jButton20.setText("Update/Delete Data");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 140, -1));

        jButton21.setText("Query Mode");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 140, -1));

        jToggleButton1.setText("Edit Mode");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 140, -1));

        jButton22.setText("Update");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 70, -1));

        jButton23.setText("Revert");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 70, -1));

        jMenu2.setText("Account Settings");

        jMenuItem1.setText("Change Username");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Change password");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("About");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(966, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SelectedTable = 1;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("TableID");
            model.addColumn("Film Name");
            model.addColumn("Film Length");
            model.addColumn("Genere");
            model.addColumn("Hall");
            model.addColumn("Date of screening");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select idspored, film.ime as \"Ime filma\", to_char(TRAJANJE,'HH:MI') as \"Trajanje\", IMEZVRSTI as \"Zvrst\" , dvorana.ime as \"Dvorana\", DATUMPREDVAJANJA as \"Datum predvajanja\" from zvrst\n"
                    + "inner join film using(idzvrst)\n"
                    + "inner join SPORED using(idfilm)\n"
                    + "inner join dvorana using(iddvorana)\n"
                    + "order by DATUMPREDVAJANJA asc");
            con.commit();

            //naredi jtable da dela for the love of god!
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDate(6).toString()});
            }

            rs.close();
            con.close();
            stm.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "An error accured! \n" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SelectedTable = 2;
        try {

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("IDDvorana");
            model.addColumn("Hall name");
            model.addColumn("Number of seats");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("SELECT * from DVORANA order by IDDVORANA asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(3)});
            }
            rs.close();
            con.close();
            stm.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainOverview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SelectedTable = 3;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Movie ID");
            model.addColumn("Movie name");
            model.addColumn("Length (HH:MI)");
            model.addColumn("Genre");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select IDFILM, IME, TO_CHAR(TRAJANJE,'HH:MI'), IMEZVRSTI from FILM\n"
                    + "inner join ZVRST USING (idzvrst)\n"
                    + "order by IDFILM asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            rs.close();
            con.close();
            stm.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SelectedTable = 4;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Movie ID");
            model.addColumn("Movie Name");
            model.addColumn("Person ID");
            model.addColumn("Person Name");
            model.addColumn("Role");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select IDFILM, FILM.IME, IDOSEBA, oseba.ime, vloga from FILM\n"
                    + "full join FILM_OSEBA USING(idfilm)\n"
                    + "full join oseba using (idoseba)\n"
                    + "order by IDFILM asc");
            con.commit();

            while (rs.next()) {
                if (rs.getInt(1) == 0) {
                    model.addRow(new Object[]{"null", rs.getString(2), rs.getInt(3), rs.getString(4), rs.getString(5)});
                }
                if (rs.getInt(3) == 0) {
                    model.addRow(new Object[]{rs.getInt(1), rs.getString(2), "null", rs.getString(4), rs.getString(5)});
                }
                if (rs.getInt(1) != 0 && rs.getInt(3) != 0) {
                    model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getString(4), rs.getString(5)});
                }
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SelectedTable = 5;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Person ID");
            model.addColumn("Name");
            model.addColumn("Surname");
            model.addColumn("Date of birth (YYYY-MM-DD)");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select * from OSEBA\n"
                    + "order by idoseba asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getDate(4).toString()});
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SelectedTable = 6;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Genre ID");
            model.addColumn("Genre Name");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select * from Zvrst\n"
                    + "order by idzvrst asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2)});
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SelectedTable = 7;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Ticket ID");
            model.addColumn("Price");
            model.addColumn("Seat");
            model.addColumn("Buyer");
            model.addColumn("Movie");
            model.addColumn("Hall");
            model.addColumn("Date of screening");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select IDVSTOPNICA, CENA, SEDEŽ, kupec.ime, film.ime, dvorana.ime, DATUMPREDVAJANJA from KUPEC\n"
                    + "inner join VSTOPNICA using (IDKUPEC)\n"
                    + "inner join SPORED using (idspored)\n"
                    + "inner join dvorana using(iddvorana)\n"
                    + "inner join film using (idfilm)\n"
                    + "order by IDVSTOPNICA asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2) + "€", rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getDate(7).toString()});
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SelectedTable = 8;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Customer ID");
            model.addColumn("Name");
            model.addColumn("Surname");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select * from KUPEC\n"
                    + "order by idkupec asc");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3)});
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        SelectedTable = 9;
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Review ID");
            model.addColumn("Score");
            model.addColumn("Comment");
            model.addColumn("Movie");
            model.addColumn("Reviewer Name");

            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;

            stm = con.createStatement();
            con.setAutoCommit(false);
            rs = stm.executeQuery("select IDODZIVI, OCENA, KOMENTAR, film.ime, kupec.ime from FILM\n"
                    + "full join ODZIVI using (idfilm)\n"
                    + "inner join kupec using (idkupec)\n"
                    + "order by IDODZIVI");
            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }

            rs.close();
            con.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new SporedInsert().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        new DvoranaInsert().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        new FilmInsert().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new FilmOsebaInsert().setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        new OsebaInsert().setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        new ZvrstInsert().setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        new VstopnicaInsert().setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new KupecInsert().setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        new OdziviInsert().setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("User ID");
            model.addColumn("Username");
            model.addColumn("Role / Premission");
            jTable1.setModel(model);

            Connection con = OracleConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = null;
            con.setAutoCommit(false);
            rs = st.executeQuery("select iduser, usn, right from USERS\n"
                    + "inner join USERRIGHTS using (IDRIGHTS)\n"
                    + "order by iduser asc");

            con.commit();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3)});
            }

            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(jTable1.getSelectedRow() + ", col: " + jTable1.getSelectedColumn());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            jTable1.setEnabled(true);
            jButton22.setVisible(true);
            jButton23.setVisible(true);
        } else {
            jTable1.clearSelection();
            jTable1.setEnabled(false);
            jButton22.setVisible(false);
            jButton23.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new PassChange().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        StaticVars.purge();
        JOptionPane.showMessageDialog(rootPane, "Sucsessfully logged out!");
        new FirstScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new UsnChange().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

        try {
            /*update <imetab>
        set <colnames> = <value>
        where id = id;  
             */
            Connection con = OracleConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = null;

            con.setAutoCommit(false);

            rs = st.executeQuery("select * from " + getSelectedTable());
            ResultSetMetaData rsmd = rs.getMetaData();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    if (jTable1.getValueAt(i, j) == null) {
                        System.out.println("update " + getSelectedTable() + " set " + model.getColumnName(j + 1) + " to '" + jTable1.getValueAt(i, j) + "' where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                    }
                    if (getSelectedTable().equals("FILM")) {
                        if (rsmd.getColumnName(j + 1).equals("TAJANJE")) {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to to_date('" + jTable1.getValueAt(i, j).toString() + "','HH:MI') where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        } else {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to '" + jTable1.getValueAt(i, j).toString().replace("'", "''") + "' where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        }
                    } else if (getSelectedTable().equals("SPORED")) {
                        if (rsmd.getColumnName(j + 1).equals("DATUMPREDVAJANJA")) {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to to_date('" + jTable1.getValueAt(i, j).toString() + "','yyyy-mm-dd') where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        } else {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to '" + jTable1.getValueAt(i, j).toString().replace("'", "''") + "' where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        }
                    } else if (getSelectedTable().equals("OSEBA")) {
                        if (rsmd.getColumnName(j + 1).toString().equals("DATUMROJSTVA")) {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to to_date('" + jTable1.getValueAt(i, j).toString() + "','YYYY-MM-DD') where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        } else {
                            System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to '" + jTable1.getValueAt(i, j).toString().replace("'", "''") + "' where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                        }
                    } else {
                        System.out.println("update " + getSelectedTable() + " set " + rsmd.getColumnName(j + 1) + " to '" + jTable1.getValueAt(i, j).toString().replace("'", "''") + "' where " + model.getColumnName(0) + " = " + jTable1.getValueAt(i, 0));
                    }
                }
                System.out.println();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        new QueryMode().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        new UpdateData().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
         new About().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainOverview().setVisible(true);
            }
        });
    }

    public static String getSelectedTable() {
        String s = "";
        switch (SelectedTable) {
            case 1:
                s = "SPORED";
                break;
            case 2:
                s = "DVORANA";
                break;
            case 3:
                s = "FILM";
                break;
            case 4:
                s = "FILM_OSEBA";
                break;
            case 5:
                s = "OSEBA";
                break;
            case 6:
                s = "ZVRST";
                break;
            case 7:
                s = "VSTOPNICA";
                break;
            case 8:
                s = "KUPEC";
                break;
            case 9:
                s = "ODZIVI";
                break;
            default:
                s = "0";
        }
        return s;
    }

    public void adjustView() {
        String role = StaticVars.g_strRole;

        if (role.equals("2")) {
            jButton10.setVisible(false);
            jButton11.setVisible(false);
            jButton12.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            jButton17.setVisible(false);
            jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel3.setVisible(false);
            jToggleButton1.setVisible(false);
            jLabel2.setVisible(false);
            jButton21.setLocation(680, 310);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
