/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author n3-21
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 6, -1, -1));

        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setText("Confirm password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setText("Surname");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, -1));

        jButton1.setText("Register!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int intID;

        char[] tab, tab2;
        String usn = jTextField1.getText(), pass = "", pass1 = "";
        String strSql = "";
        
        if(usn.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Username is a requierd field!");
            return;
        }
        
        if(!checkUsn(usn)){
            JOptionPane.showMessageDialog(rootPane, "Username already exists. Try using: "+genUsn(usn));
            return;
        }
        
        

        tab = jPasswordField1.getPassword();
        tab2 = jPasswordField2.getPassword();
        
        for (char c : tab) {
            pass +=c;
        }
        for (char c : tab2) {
            pass1 +=c;
        }
       
        
        if(pass.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Password is a requierd field!");
            return;
        }
        
        if(pass1.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please, retype the password!");
            return;
        }
        
        
        if(!checkPasswd(pass, pass1)){
            JOptionPane.showMessageDialog(rootPane, "Passwords do not match");
            return;
        }
        
        pass = StaticVars.getMd5(pass);
        
        
        Connection connection = OracleConnection.getConnection();
        
        Statement statement = null;



        
       
       
        try {
            //vnos nove stranke
            
               
                intID = getID();
               
                strSql = "insert into users (IDUSER,USN,PASSWD,NAME,SURNAME,IDRIGHTS)";
                strSql = strSql + "values ("+intID+",'"+usn+"','"+pass+"',";
                strSql = strSql + "'"+jTextField2.getText()+"','"+ jTextField3.getText()+"',2)";
                
                statement = connection.createStatement();
               
                connection.setAutoCommit(false);
                
                statement.execute(strSql);
               
                connection.commit();
                JOptionPane.showMessageDialog(rootPane, "Sucsessfully registered!");
                new login().setVisible(true);
                dispose();

           
           

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage());
        } finally {
            try {
                statement.close();
            } catch (Exception e) {
            }
            try {
                connection.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FirstScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    
    
    public static boolean checkPasswd(String pass1, String pass2){
        return pass1.equals(pass2);
    }
    
    public static boolean checkUsn(String usn){
        Connection connection = OracleConnection.getConnection();
        Statement stm = null;
        ResultSet rs = null;
        String SQL = "select usn from users";
        
            
        
        
    try{
        stm = connection.createStatement();
        connection.setAutoCommit(false);
        rs = stm.executeQuery(SQL);
        connection.commit();
        while(rs.next()){
            if (usn.equals(rs.getString(1))){
                return false;
            }
        
        }
        
        connection.close();
        stm.close();
        rs.close();
    }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"An unexpected error accured! \n error: "+e.getMessage());
            return false;
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"An unexpected error accured! \n error: "+e.getMessage());
        return false;
    }
        
        
    
    return true;
    }  
    
    public static String genUsn(String usn) {
        return usn+(char)(Math.random()*26+65)+(int)(Math.random()*(usn.length()*2)+1);
    }
    
    private int getID() throws Exception {
        final Connection connection = OracleConnection.getConnection();
        Statement stmt = null;
        ResultSet rs = null;
        int id = 0;
        stmt = connection.createStatement();
        rs = stmt.executeQuery("SELECT max(idUser) FROM users");
        if (rs.next()) {
            id = rs.getInt(1);
        }
        connection.close();
        return id + 1;        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
