package demo;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FireBlazeTSETSR
 */
public class VstopnicaInsert extends javax.swing.JFrame {

    /**
     * Creates new form VstopnicaInsert
     */
    public VstopnicaInsert() {
        initComponents();
        fillMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Price:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 100, -1));

        jLabel2.setText("Seat:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));

        jLabel3.setText("Customer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel4.setText("Time table");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, -1));

        jButton1.setText("Insert!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        setSize(new java.awt.Dimension(416, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Integer.parseInt(jSpinner1.getValue().toString()) <0){
            JOptionPane.showMessageDialog(rootPane, "Price cannot be negative!");
            return;
        }
        
        if(Integer.parseInt(jSpinner2.getValue().toString()) <=0){
            JOptionPane.showMessageDialog(rootPane, "Seat number must be greater than 0!");
            return;
        }
        
        try{
            Connection con = OracleConnection.getConnection();
            Statement stm = con.createStatement();
            con.setAutoCommit(false);
            
            stm.execute("insert into VSTOPNICA(IDVSTOPNICA,cena,sedež,idkupec,IDSPORED)\n" +
                "VALUES("+getID()+","+Integer.parseInt(jSpinner1.getValue().toString())+","+Integer.parseInt(jSpinner2.getValue().toString())+","
                    +Integer.parseInt(jComboBox1.getSelectedItem().toString().substring(0,jComboBox1.getSelectedItem().toString().indexOf(",")))+","
                    +Integer.parseInt(jComboBox2.getSelectedItem().toString().substring(0,jComboBox2.getSelectedItem().toString().indexOf(",")))+")");
            con.commit();
            con.close();
            stm.close();
            JOptionPane.showMessageDialog(rootPane, "Sucsessfully inserted!");
            
            jSpinner1.setValue(0);
            jSpinner2.setValue(0);
            jComboBox1.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(1);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstopnicaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstopnicaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstopnicaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstopnicaInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstopnicaInsert().setVisible(true);
            }
        });
    }
    
    public void fillMenus(){
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        try {
            Connection con = OracleConnection.getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = null;
            con.setAutoCommit(false);
            
            rs = stm.executeQuery("select IDKUPEC, ime, PRIIMEK from KUPEC\n" +
                "order by IDKUPEC asc");
            con.commit();
            while(rs.next()){
                jComboBox1.addItem(rs.getInt(1)+","+rs.getString(2)+" "+rs.getString(3));
            }
            
            
            rs = stm.executeQuery("select idspored, ime, DATUMPREDVAJANJA from SPORED\n" +
                "inner join film using(idfilm)\n" +
                "order by IDSPORED asc");
            con.commit();
            while(rs.next()){
                jComboBox2.addItem(rs.getInt(1)+","+rs.getString(2)+"; Date: "+rs.getDate(3).toString());
            }
            
            rs.close();
            stm.close();
            con.close();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VstopnicaInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public int getID(){
        int id = 0;
        try {
            Connection con= OracleConnection.getConnection();
            Statement stm = null;
            ResultSet rs = null;
            stm = con.createStatement();
            con.setAutoCommit(false);
            
            rs = stm.executeQuery("select max(idVstopnica) from Vstopnica");
            con.commit();
            while(rs.next())
               id = rs.getInt(1);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return id+1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
